apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopnow-umbrella
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aviral31/shopNow'
    targetRevision: HEAD
    path: kubernetes/argocd/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: aviral-k8
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
