apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: aviral-k8
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: 975050024946.dkr.ecr.ca-central-1.amazonaws.com/shopnow-aviral/admin:latest #<account-id>.dkr.ecr.<region>.amazonaws.com/shopnow/admin:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        # If you want to override baked-in nginx config, uncomment volumeMount and use ConfigMap below.
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: admin-nginx-conf

