apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace: aviral-k8
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
      
      # Frontend API - proxy to backend for aviral
      location /aviral/api/ {
        proxy_pass http://backend:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 90;
      }
      
      # Handle static assets within /aviral/static/ - map to /static/
      location /aviral/static/ {
        alias /usr/share/nginx/html/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
      }
      
      # Handle other static assets (favicon, etc.) within /aryan/
      location ~ ^/aviral/(.*\.(css|js|map|svg|gif|png|jpg|jpeg|ico|woff2?|ttf|eot))$ {
        alias /usr/share/nginx/html/$1;
        expires 30d;
        add_header Cache-Control "public, immutable";
      }
      
      # Handle /aviral path - serve the React app
      # This catches all paths and serves index.html for SPA routing
      location / {
        try_files $uri $uri/ /index.html;
      }
      
      # Health check
      location = /health { 
        return 200 'OK'; 
        add_header Content-Type text/plain; 
      }
      
      # Security headers
      add_header X-Content-Type-Options nosniff;
      add_header X-Frame-Options DENY;
    }

