apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  namespace: aviral-k8
  labels:
    app: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017

